version: '3.1'


services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD} 
    volumes:
      - /var/lib/postgresql
    ports: 
      - "${PSQL_PORT}:5432"


