version: '3.1'

services:
  web:
    container_name: quiz
    build: ./
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    ports: 
      - 9000:8000
    env_file: ./.env
    depends_on: 
      postgres:
        condition: service_healthy
      
  postgres:
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
    image: postgres:13.3
    container_name: psdb
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_PASSWORD: ${PSQL_PASSWORD} 
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
